name: Deploy Blazor WASM to GitHub Page
env:
  PUBLISH_DIR: bin/Release/net7.0/publish/wwwroot
  
on:
	push:
		branches: [ master ]

jobs:
	build:
		runs-on: ubuntu-latest
		steps:
			- name: Checkout
				uses: actions/checkout@v3.3.0

			- name: Publish application
				run: dotnet publish -c Release

			- name: Add .nojekyll file
				run: touch release/wwwroot/.nojekyll

			- name: Commit wwwroot to GitHub pages
				uses: JamesIves/github-pages-deploy-action@3.7.1
				with:
					GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
					BRANCH: gh-pages
					FOLDER: release/wwwroot
