name: Deploy Blazor WASM to GitHub Page

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      pages: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.0.3

    - name: Publish .NET Core Project
      run: dotnet publish "Simple Showcase.csproj" -c Release -o release --nologo

    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.3
      with:
        
        
